### ISSUE TITLE
tmlibs vs tm-cmn

### ISSUE THREAD

**Issue by b00f** [tendermint/tm-cmn#11]
Tendermint had a repo named [tmlibs](https://github.com/tendermint/tmlibs) which is deprectaed and marge to tendermint.
Now `tm-cmn` is introduced which will cause some compile errors for sure. Some packages are using `tendermint/tendermint/libs` some are using `tendermint/tm-cm`.
During the race better not change the horses!

**Comment by marbar3778** [comment]
as of now, only the db package has been stripped from tendermint, other things will be duplicated to try to avoid this. I am trying to mainly remove tendermint as a depndancy in the iavl repo and belive this will help others in using updated code but not having to update tendermint itself. If you run into issues please make them clear and I will aim to solve them as soon as possible

**Comment by b00f** [comment]
May I know what is the reason moving db package out of tendermint library? 
Cosmos also need to be updated as well.

**Comment by marbar3778** [comment]
the main reason was to remove tendermint as a dependancy in the iavl tree, yes cosmos has to be updated, when the tendermint, or iavl versions are updated to the most recent versions, I have already tested it, but since they only use 32.1 and we haven't done a release with this update, there isnt a need to do it right now

**Comment by b00f** [comment]
The good, the bad and the ugly. This trilemma always repeats.

**Comment by marbar3778** [comment]
I am hoping to move away from this with this repo, if you have any ideas on how to approach this better, I am all ears, we value your input.
